"""empty message

Revision ID: 12a23a843798
Revises: 7ad4f4e9edc8
Create Date: 2021-02-05 22:06:10.533161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a23a843798'
down_revision = '7ad4f4e9edc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_apps_deleted'), 'apps', ['deleted'], unique=False)
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_deleted'), 'users', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted'), table_name='users')
    op.drop_column('users', 'deleted')
    op.drop_index(op.f('ix_apps_deleted'), table_name='apps')
    op.drop_column('apps', 'deleted')
    # ### end Alembic commands ###
